version: "3.8"

services:
  app:
    build:
      context: ./backend/docker/php
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  web:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./src:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: